name = "PartialFunctions"
uuid = "570af359-4316-4cb7-8c74-252c00c2016b"
authors = ["Thomas Marks <marksta@umich.edu> and contributors"]
version = "1.0.3"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
